ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "brandPrimaryColor" TEXT NOT NULL DEFAULT '#6D28D9',
ADD COLUMN IF NOT EXISTS "brandAccentColor" TEXT NOT NULL DEFAULT '#F5F3FF';

ALTER TABLE "Invoice"
ADD COLUMN IF NOT EXISTS "shareToken" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_shareToken_key" ON "Invoice"("shareToken");
